=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dialogue ((personnage | background-image | middle-image)*, personnage)>
<!ELEMENT personnage (text | background-image | middle-image)*>
    <!ATTLIST personnage name CDATA #REQUIRED>
    <!ATTLIST personnage pos (0|1|2|3|4|5) #IMPLIED>
    <!ATTLIST personnage noimage CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT background-image (#PCDATA)>
<!ELEMENT middle-image (#PCDATA)>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE questionnaire SYSTEM "dialog.dtd">-->

<dialogue name="Plongee">
    <personnage name="hero">
        <text> Pfiou, j'ai eu chaud ! Heureusement que - Aïe aïe aïe ! </text>
    </personnage>
    <personnage name="genie">
        <text> Heureusement que t'as la tête dur toi ! </text>
    </personnage>
    <personnage name="hero">
        <text> Bon, qu'est-ce qui se passe ici ?! C'était quoi ça, là-haut ?! Et où est-ce que j'ai encore atteri ?! </text>
    </personnage>
    <personnage name="genie">
        <text> Bah, dans une caverne du monde des Maths ! C'est pourtant évident ! </text>
    </personnage>
    <personnage name="hero">
        <text> Le monde des Maths ? Alors ça doit être pour ça que je comprends rien, je suis nul en maths... </text>
    </personnage>
    <personnage name="genie">
        <text> Avançons. Je t'expliquerai en chemin. </text>
        <text> Autrefois, le monde des Maths était paisible. Les hommes et les expressions mathématiques vivaient en harmonie.</text>
        <text> Nul problème n'était insovable. Et puis... Vektor est arrivé. </text>
    </personnage>
    <personnage name="hero">
        <text> Vektor ? </text>
    </personnage>
    <personnage name="genie">
        <text> L'homme que tu as aperçu tout à l'heure. C'est le seigneur des Mathémaléfices. </text>
        <text> C'est à cause de lui que le monde des maths est si obscure et que ces expressions t'ont attaqué. </text>
        <text> Son plan est de faire tendre la difficulté des maths vers l'infini... </text>
    </personnage>
    <personnage name="hero">
        <text> Ben il doit vraiment s'ennuyer... </text>
    </personnage>
    <personnage name="genie">
        <text> C'est très grave ! Si personne ne l'arrête, il - </text>
    </personnage>
    <personnage name="ennemi">
        <text> C'est lui ! Attrapez-le ! </text>
    </personnage>
    <personnage name="genie">
        <text> Les sbires de Vektor ! Il y a une rivière pas loin, vite, cours et saute dedans !</text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">

<dialogue>
    <personnage name="hero" pos="0">
        <text> Euh... T'es sûr que c'était de la magie ça ? Ca ressemblait plutôt à de la sorcellerie... </text>
    </personnage>
    <personnage name="genie" pos="1">
        <text> C'était de la magie ! De la mathémagie noire ! </text>
    </personnage>
    <personnage name="mathrandir" pos="3">
        <text> Ma mathémagie a été vaincue... Je reconnais la puissance de ta logique, jeune inconnu. </text>
        <text> L'artefact est à toi. </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue06.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">

<dialogue>
    <personnage name="hero" pos="0">
        <text> C'est vous les sages du village ? J'ai des questions à vous poser !</text>
    </personnage>
    <personnage name="gwendouille" pos="2">
        <text> Hein quoi ? tu vois pas qu'on a mieux que ça à faire ? La machine à café est cassée ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais je - </text>
    </personnage>
    <personnage name="gwendouille" pos="2">
        <text> Qu'est-ce qu'on va faire sans notre café Audib ? </text>
    </personnage>
    <personnage name="audib" pos="3">
        <text> J'en ai aucune idée Gwendouille ! Sans café au bout de 24 heures, j'ai des tremblements, des sueurs froides... </text>
        <text> Eh ! Et si il réparait notre machine ! </text>
    </personnage>
    <personnage name="gwendouille" pos="2">
        <text> Bonne idée Audib ! Allez toi, répare notre machine ! En échange, on  répondra à tes questions. </text>
        <text> Allez et que ça saute, je veux un arabica bien noir ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Hm... On dirait bien qu'il y a un problème dans la tuyauterie de leur machine... </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">
<<<<<<< HEAD


<dialogue>
    <background-image>menu principal</background-image>
    <personnage name="hero" pos="0">
        <text> Mais... Où suis-je ? J'étais en cours il n'y a même pas 5 minutes... Eh ! Il y a quelqu'un ? </text>
        <text> Qu'est-ce qui se passe ici... Aïe ! </text>
        <text> Qu'est-ce que je fous avec cette m... </text>
    </personnage>
    <personnage name="genie" pos="3">
        <text> Eh bah, t'en as mis du temps à me sortir de là ! </text>
=======
<dialogue>
    <background-image name="paysage"/>
    <personnage name="hero" pos="0">
        <text> Mais... Où suis-je ? J'étais en cours il n'y a même pas 5 minutes... </text>
        <text> Eh ! Il y a quelqu'un ?</text>
        <text> Qu'est-ce qui se passe ici... Aïe !</text>
        <text> Qu'est-ce que je fous avec cette m... </text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Eh bah, t'en as mis du temps à me sortir de là, %h ! </text>
>>>>>>> 45fb5196725771ea23c7f546bea79d9ee5310b01
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais qui êtes-vous ?! Et qu'est-ce que je fais là ? Et on est où d'abord ? </text>
    </personnage>
<<<<<<< HEAD
    <personnage name="genie" pos="3">
=======
    <personnage name="pyles" pos="3">
>>>>>>> 45fb5196725771ea23c7f546bea79d9ee5310b01
        <text> Hola, hola ! Doucement, une question à la fois. Je suis Pylès, le génie des mathématiques. Et ici, nous sommes à - </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Qu'est-ce qui se passe ?! </text>
    </personnage>
<<<<<<< HEAD
    <personnage name="genie" pos="3">
        <text> Nom de Zeus ! Les légions d'expressions mathémaéfiques de Vektor ! </text>
    </personnage>
    <personnage name="ennemis" noimage="">
        <text> Ecrasez-le ! </text>
    </personnage>
</dialogue>
=======
    <personnage name="pyles" pos="3">
        <text> Nom de Zeus ! Les légions d'expressions mathémaléfiques de Viktor ! </text>
    </personnage>
    <personnage name="ennemis" noimage="">
        <text> Ecrasez-le ! ! !</text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Écoutes-moi bien ! Il faut absolument que ces expressions ne t'attrapent pas ! Cours à travers la forêt pour leur échapper. </text>
        <text> Utilise les flèches pour te déplacer et surtout, ne laisse personne t'approcher ! </text>
        <text> Si tu vois un objet par-terre, tu peux le prendre mais je ne garantis pas le résultat... </text>
        <text> Aller je file, on se revoit de l'autre côté !</text>
    </personnage>
    <endbutton name="continue">Partir en courant dans la forêt</endbutton>
</dialogue>
>>>>>>> 45fb5196725771ea23c7f546bea79d9ee5310b01

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue09.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">

<dialogue>
    <personnage name="hero" pos="0">
        <text> Mais qui c'est encore ce guignol ? </text>
        <text> Eh ! Tu bloques le passage papy ! </text>
    </personnage>
    <personnage name="mathrandir" pos="3">
        <text> Je suis un serviteur de la mathémagie, détenteur de la fonction inverse ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais qu'est-ce qu'il raconte ?! Eh ! Je comprends rien ! </text>
    </personnage>
    <personnage name="mathrandir" pos="3">
        <text> Dériver la conversation ne vous servira à rien ! Repartez dans l'ombre ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Je veux juste - </text>
    </personnage>
    <personnage name="mathrandir" pos="3">
        <text> VOUS - NE - PASSEREZ - PAS !</text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais c'est quoi ces co- </text>
    </personnage>
    <personnage name="genie" pos="1">
        <text> C'est Mathrandir, le mathémagicien gris ! On dirait qu'il veut t'empêcher de prendre l'artefact. </text>
        <text> Tu vas devoir briser sa mathémagie en conjurant la fonction x² pour passer. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Et je fais comment ? </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue02b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">
<dialogue>
    <background-image name="caverne"/>
    <personnage name="hero" pos="0">
        <text> Un "monde des maths" tu disais ?</text>
    </personnage>
    <personnage name="pyles" pos="3">
    <text> Oui, autrefois le monde des Maths était paisible. Les hommes et les expressions mathématiques vivaient en harmonie.</text>
    <text> Nul problème n'était insolvable. Et puis... Vektor est arrivé. </text>
    </personnage>
    <personnage name="hero" pos="0">
    <text> Vektor ? C'était pas Viktor ?</text>
    </personnage>
    <personnage name="pyles" pos="3">
    <text> Oh commence pas, je sais déjà même pas pourquoi je suis là à te parler ...</text>
    <text> L'homme que tu as aperçu tout à l'heure. C'est le seigneur des Mathémaléfices. </text>
    <text> C'est à cause de lui que le monde des maths est si obscure et que ces expressions t'ont attaqué. </text>
    <text> Son plan est de faire tendre la difficulté des maths vers l'infini... </text>
    </personnage>
    <personnage name="hero" pos="0">
    <text> Ben il doit vraiment s'ennuyer... </text>
    </personnage>
    <personnage name="pyles" pos="3">
    <text> C'est très grave ! Si personne ne l'arrête, il - </text>
    </personnage>
    <personnage name="ennemi" noimage="">
    <text> C'est lui ! Attrapez-le ! </text>
    </personnage>
    <personnage name="pyles" pos="3">
    <text> Les sbires de Vektor ! Il y a une rivière pas loin, vite, cours et saute dedans !</text>
    </personnage>
    <endbutton name="continue">Courir et rater son plongeon</endbutton>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">

<dialogue>
    <personnage name="genie" pos="3">
        <text> Regarde ! Voici le monde des maths. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais comment vais-je faire pour sortir d'ici ? </text>
    </personnage>
    <personnage name="genie" pos="3">
        <text> Tu vois la tour là-bas ? C'est l'antre de Vektor. On raconte qu'un protail vers un autre monde serait caché sous sa tour. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Alors j'ai juste à trouver ce portail pour m'échapper non ? </text>
    </personnage>
    <personnage name="genie" pos="3">
        <text> Ha ha, ça serait beaucoup trop simple ! A cause de Vektor, tous les problèmes sont de plus en plus compliqués. </text>
        <text> Ca te concerne aussi ! Si tu arrivais à affaiblir les pouvoirs de Vektor, tu réussirais peut-être à sortir d'ici. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Et comment est-ce que je peux l'affaiblir ? </text>
    </personnage>
    <personnage name="genie" pos="3">
        <text> Qu'est-ce que j'en sais moi ? Commence par aller au village, tu trouveras sûrement quelqu'un pour t'aider. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais ... </text>
        <text> Le village hein ... </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/arrivee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">
<dialogue>
    <background-image>menu principal</background-image>
    <personnage name="hero" pos="0">
        <text> Mais... Où suis-je ? J'étais en cours il n'y a même pas 5 minutes... </text>
        <text> Eh ! Il y a quelqu'un ?</text>
        <text> Qu'est-ce qui se passe ici... Aïe !</text>
        <text> Qu'est-ce que je fous avec cette m... </text>
    </personnage>
    <background-image>menu principal</background-image>
    <personnage name="pyles" pos="3">
        <text> Eh bah, t'en as mis du temps à me sortir de là, %h ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Mais qui êtes-vous ?! Et qu'est-ce que je fais là ? Et on est où d'abord ? </text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Hola, hola ! Doucement, une question à la fois. Je suis Pylès, le génie des mathématiques. Et ici, nous sommes à - </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Qu'est-ce qui se passe ?! </text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Nom de Zeus ! Les légions d'expressions mathémaléfiques de Viktor ! </text>
    </personnage>
    <personnage name="ennemis" noimage="">
        <text> Ecrasez-le !!</text>
    </personnage>
    <endbutton name="continue">Partir en courant dans la forêt</endbutton>
</dialogue>
