=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dialogue ((personnage | background-image | middle-image)*, personnage)>
<!ELEMENT personnage (text | background-image | middle-image)*>
    <!ATTLIST personnage name CDATA #REQUIRED>
    <!ATTLIST personnage pos (0|1|2|3|4|5) #IMPLIED>
    <!ATTLIST personnage noimage CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT background-image (#PCDATA)>
<!ELEMENT middle-image (#PCDATA)>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE questionnaire SYSTEM "dialog.dtd">-->

<dialogue name="Information">
    <personnage name="hero">
        <text> Voilà, c'est réparé ! Maintenant, expliquez-moi comment affaiblir Vektor. </text>
    </personnage>
    <personnage name="gwendouille">
        <text> Affaiblir Viktor ? Ta question est bizarre mais on va quand même te répondre. </text>
    </personnage>
    <personnage name="audib">
        <text> Le pouvoir de Vektor repose sur le portail sur lequel est construit sa tour. </text>
        <text> Elle draine l'énergie du portail, et Vektor se sert de ça pour lancer ses mathémaléfices et rendre les maths encore plus compliquées. </text>
    </personnage>
    <personnage name="hero">
        <text> Donc je dois détruire sa tour pour l'affaiblir ? </text>
    </personnage>
    <personnage name="gwendouille">
        <text> Ah ! Comme si c'était simple ! </text>
        <text> La Tour de Vektor a été construite à l'aide d'anciens outils mathémagiques qu'ont utilisé les dieux pour bâtir notre monde. </text>
    </personnage>
    <personnage name="hero">
        <text> Des outils mathémagiques ? </text>
    </personnage>
    <personnage name="audib">
        <text> Oui. Quiconque possède ces artefacts peut construire et détruire à loisir. </text>
        <text> Malheureusement après les avoir utilisés pour ses noirs desseins, Vektor a caché ces artefacts dans 3 sanctuaires gardés par ses sbires. </text>
    </personnage>
    <personnage name="hero">
        <text> Et où sont ces santuaires ? </text>
    </personnage>
    <personnage name="audib">
        <text> Personne ne le sait vraiment. Les gens parlent d'une forêt, d'un lac et des nuages... </text>
        <text> Tu les trouveras sans doutes aux alentours du village. </text>
    </personnage>
    <personnage name="hero">
        <text> D'accord. Merci ! </text>
    </personnage>
    <personnage name="audib">
        <text> N'hésites pas à revenir nous voir si tu as des questions. </text>
    </personnage>
    <personnage name="gwendouille">
        <text> Mais ramènes du café ! </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE questionnaire SYSTEM "dialog.dtd">-->

<dialogue name="Village">
    <personnage name="habitant1">
        <text> Heureusement que les deux sages de l'auberge sont là pour répondre à nos questions ... </text>
    </personnage>
    <personnage name="habitant2">
        <text> La vie est devenue plus difficile à cause des mathémaléfices de Vektor. </text>
        <text> Mais j'ai l'impression que les deux sages de l'auberge ne sont pas affecté par ça. </text>
    </personnage>
    <personnage name="habitant3">
        <text> Bienvenue au village, étranger ! Si tu as un problème, tu ferais mieux d'aller faire un tour à l'auberge et de parler aux sages. </text>
    </personnage>
    <personnage name="genie">
        <text> T'écoutes ce qu'on te dit un peu ? Va voir les sages de l'auberge ! </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue19.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">

<dialogue>
    <personnage name="hero" pos="0">
        <text> Bon. Il est l'heure pour moi de partir... Merci Pylès. Merci pour tout. </text>
    </personnage>
    <personnage name="genie" pos="3">
        <text> Oh tu sais... moi j'ai juste fait ça pour qu'ils recommencent à produire des Pringles. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Adieu Pylès ! </text>
    </personnage>
    <personnage name="genie" pos="3">
        <text> Au revoir ! </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue02a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">
<dialogue>
    <background-image name="caverne"/>
    <personnage name="hero" pos="0">
        <text> Pfiou, j'ai eu chaud ! Heureusement que - Aïe aïe aïe ! </text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Heureusement que t'as la tête dur toi ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Bon, qu'est-ce qui se passe ici ?! C'était quoi ça, là-haut ?! Et où est-ce que j'ai encore atteri ?! </text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Bah, dans une caverne du monde des Maths ! C'est pourtant évident ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Le monde des Maths ? Alors ça doit être pour ça que je comprends rien, je suis nul en maths... </text>
    </personnage>
    <personnage name="pyles" pos="3">
        <text> Avançons. Je t'expliquerai en chemin. </text>
    </personnage>
    <endbutton name="continue">Le suivre</endbutton>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogue SYSTEM "dialog.dtd">

<dialogue>
    <personnage name="hero" pos="0">
        <text> Gloups... Je crois que j'ai le vertige... </text>
    </personnage>
    <personnage name="genie" pos="1">
        <text> Oh ! Regarde, on voit l'auberge d'ici ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> J'ai envie de descendre, ou je vais finir par vomir... </text>
    </personnage>
    <personnage name="cullen" pos="3">
        <text> Tiens, tiens, tiens... des visiteurs. </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Il n'y a personne de normal dans ce pays ? </text>
    </personnage>
    <personnage name="cullen" pos="3">
        <text> Silence, petit impertinent ! Je sais qui tu es et ce que tu essaies de faire ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Vous voudriez pas m'aider par hasard ? </text>
    </personnage>
    <personnage name="cullen" pos="3">
        <text> Imbécile ! Je suis Cullen ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Hein ? Comme Edward dans Twilight ? </text>
    </personnage>
    <personnage name="cullen" pos="3">
        <text> Mais non ! Comme les nombres, idiot ! Je suis le bras droit de Vektor ! </text>
    </personnage>
    <personnage name="hero" pos="0">
        <text> Ah... donc j'imagine que c'est non pour l'aide... </text>
    </personnage>
    <personnage name="genie" pos="1">
        <text> Regarde ! Dans sa main ! C'est un artefact ! </text>
    </personnage>
    <personnage name="cullen" pos="3">
        <text> Vous ne l'aurez jamais ! Il faudra me battre pour ça ! </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE questionnaire SYSTEM "dialog.dtd">-->

<dialogue name="enigme">
    <personnage name="hero">
        <text> Le ciel a l'ai bizarre de ce côté-là... Je devrais aller y jeter un oeil. </text>
    </personnage>
    <personnage name="genie">
        <text> Je sens qu'un puissant mathémaléfice est à l'oeuvre ici... </text>
    </personnage>
    <personnage name="hero">
        <text> Tu crois que je devrais y entrer ? </text>
    </personnage>
    <personnage name="genie">
        <text> Moi j'ai pas envie mais toi t'es un peu obligé, y'a rien après cette grotte, et faut bien suivre le scénario ! </text>
    </personnage>
    <personnage name="hero">
        <text> Quoi ? </text>
    </personnage>
    <personnage name="genie">
        <text> Rien, c'est de la mathémagie. </text>
    </personnage>
    <personnage name="hero">
        <text> ... </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE questionnaire SYSTEM "dialog.dtd">-->

<dialogue name="towers">
    <personnage name="hero">
        <text> Waow ! </text>
    </personnage>
    <personnage name="genie">
        <text> Allez, qu'est-ce que tu attends pour détruire cette tour ? </text>
    </personnage>
    <personnage name="hero">
        <text> Ben... D'habitude tu me dis comment faut faire alors... </text>
    </personnage>
    <personnage name="genie">
        <text> Bon d'accord ! Faut vraiment tout t'expliquer à toi ! </text>
    </personnage>
</dialogue>

=== naomiHauret/Odyss-e-des-maths/android/assets/texts/dialogs/dialogue03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE questionnaire SYSTEM "dialog.dtd">-->

<dialogue name="Accrobranche">
    <personnage name="genie">
        <text> Bravo, tu as réussis à les semer ! Heureusement que tu sais nager ! </text>
    </personnage>
    <personnage name="hero">
        <text> Tu parles ! J'ai cru que j'allais me noyer... Bon, comment on sort d'ici ? </text>
    </personnage>
    <personnage name="genie">
        <text> Commences déjà par avancer, ça serait pas mal. </text>
    </personnage>
    <personnage name="hero">
        <text> On dirait les racines d'un arbre... </text>
    </personnage>
    <personnage name="genie">
        <text> Pas des racines ! Des racines carrés ! </text>
    </personnage>
    <personnage name="hero">
        <text> On est vraiment au pays des Maths ici... Je me demande si je peux atteindre la surface en les escaladant ? </text>
    </personnage>
</dialogue>
